### ISSUE TITLE
Upload to OPS fails

### ISSUE THREAD

**Issue by danielkinahan** [ligh7s/smoked-salmon#44]
I can see the upload just fine but it doesn't generate the torrent file for me.

```
No requests were found on OPS (searchstrs: *********)
Generating torrent file... done!
Uploading torrent...
Traceback (most recent call last):
  File "/smoked-salmon/run.py", line 13, in <module>
    commandgroup(obj={})
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/smoked-salmon/salmon/uploader/__init__.py", line 145, in up
    upload(
  File "/smoked-salmon/salmon/uploader/__init__.py", line 286, in upload
    torrent_id = prepare_and_upload(
                 ^^^^^^^^^^^^^^^^^^^
  File "/smoked-salmon/salmon/uploader/upload.py", line 68, in prepare_and_upload
    torrent_id = loop.run_until_complete(gazelle_site.upload(data, files))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/smoked-salmon/salmon/trackers/base.py", line 334, in upload
    return await self.site_page_upload(data, files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/smoked-salmon/salmon/trackers/base.py", line 322, in site_page_upload
    return self.parse_most_recent_torrent_and_group_id_from_group_page(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/smoked-salmon/salmon/trackers/base.py", line 416, in parse_most_recent_torrent_and_group_id_from_group_page
    return max(torrent_ids)
           ^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```

**Comment by StardOva** [comment]
I have the same problem, did you find a solution yet?

**Comment by backstab5983** [comment]
> I have the same problem, did you find a solution yet?

https://github.com/ghoto/smoked-salmon/tree/elghoto-version
https://github.com/miandru/smoked-salmon

These should work ;)

**Comment by StardOva** [comment]
I haven't looked at these, but instead just made my own fix. In `salmon/trackers/base.py` line 412 following:
```python
for pl in soup.find_all("a", class_="tooltip"):
    # this works for OPS
    torrent_url = re.search(r"torrents.php\?id=(\d+)", pl["href"])
    if not torrent_url:
        # this works for RED
        torrent_url = re.search(r"torrents.php\?torrentid=(\d+)", pl["href"])

    if torrent_url:
        torrent_ids.append(int(torrent_url[1]))
return max(torrent_ids)
```

Haven't bothered to fork the repo yet or make a pr.
